install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - ps: |
      if (!(Test-Path -Path "C:\Program Files\Java\jdk1.7.0\src.zip")) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://downloads.sourceforge.net/project/jdk7src/jdk7u10/2013-01-04/src-jdk.zip',
          'C:\Program Files\Java\jdk1.7.0\src.zip'
        )
      }
  - cmd: SET JDK_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JDK_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Xss2m
  - cmd: SET AKKA_TEST_TIMEFACTOR=3
  - cmd: mkdir .ensime_cache
build_script:
  - sbt clean compile test:compile it:compile
before_test:
  - sbt gen-ensime
test_script:
  - sbt test it:test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
  - C:\Program Files\Java\jdk1.7.0\src.zip
